import "./globals.css";
import NextAuthProvider from "@/provider/NextAuthProvider";
import ReduxProvider from "@/redux/provider";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <NextAuthProvider>
            <ReduxProvider>
                {children}
            </ReduxProvider>
        </NextAuthProvider>
        </body>
        </html>
    );
}
